<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = collect([
            ["mapId" => "01", "shortLabel" => "AG", "label" =>	"Antigua and Barbuda"],
            ["mapId" => "02", "shortLabel" => "BS", "label" =>	"Bahamas"],
            ["mapId" => "03", "shortLabel" => "BB", "label" =>	"Barbados"],
            ["mapId" => "04", "shortLabel" => "BZ", "label" =>	"Belize"],
            ["mapId" => "05", "shortLabel" => "CA", "label" =>	"Canada"],
            ["mapId" => "06", "shortLabel" => "CR", "label" =>	"Costa Rica"],
            ["mapId" => "07", "shortLabel" => "CU", "label" =>	"Cuba"],
            ["mapId" => "08", "shortLabel" => "DM", "label" =>	"Dominica"],
            ["mapId" => "09", "shortLabel" => "DO", "label" =>	"Dominican Republic"],
            ["mapId" => "10", "shortLabel" => "SV", "label" =>	"El Salvador"],
            ["mapId" => "11", "shortLabel" => "GD", "label" =>	"Grenada"],
            ["mapId" => "12", "shortLabel" => "GT", "label" =>	"Guatemala"],
            ["mapId" => "13", "shortLabel" => "HT", "label" =>	"Haiti"],
            ["mapId" => "14", "shortLabel" => "HN", "label" =>	"Honduras"],
            ["mapId" => "15", "shortLabel" => "JM", "label" =>	"Jamaica"],
            ["mapId" => "16", "shortLabel" => "MX", "label" =>	"Mexico"],
            ["mapId" => "17", "shortLabel" => "NI", "label" =>	"Nicaragua"],
            ["mapId" => "18", "shortLabel" => "PA", "label" =>	"Panama"],
            ["mapId" => "19", "shortLabel" => "KN", "label" =>	"St. Kitts & Nevis"],
            ["mapId" => "20", "shortLabel" => "LC", "label" =>	"St. Lucia"],
            ["mapId" => "21", "shortLabel" => "VC", "label" =>	"St. Vincent & the Grenadines"],
            ["mapId" => "22", "shortLabel" => "TT", "label" =>	"Trinidad & Tobago"],
            ["mapId" => "23", "shortLabel" => "US", "label" =>	"United States"],
            ["mapId" => "24", "shortLabel" => "GL", "label" =>	"Greenland"],
            ["mapId" => "25", "shortLabel" => "AR", "label" =>	"Argentina"],
            ["mapId" => "26", "shortLabel" => "BO", "label" =>	"Bolivia"],
            ["mapId" => "27", "shortLabel" => "BR", "label" =>	"Brazil"],
            ["mapId" => "28", "shortLabel" => "CL", "label" =>	"Chile"],
            ["mapId" => "29", "shortLabel" => "CO", "label" =>	"Colombia"],
            ["mapId" => "30", "shortLabel" => "EC", "label" =>	"Ecuador"],
            ["mapId" => "31", "shortLabel" => "FK", "label" =>	"Falkland Islands"],
            ["mapId" => "32", "shortLabel" => "GF", "label" =>	"French Guiana"],
            ["mapId" => "33", "shortLabel" => "GY", "label" =>	"Guyana"],
            ["mapId" => "34", "shortLabel" => "PY", "label" =>	"Paraguay"],
            ["mapId" => "35", "shortLabel" => "PE", "label" =>	"Peru"],
            ["mapId" => "36", "shortLabel" => "SR", "label" =>	"Suriname"],
            ["mapId" => "37", "shortLabel" => "UY", "label" =>	"Uruguay"],
            ["mapId" => "38", "shortLabel" => "VE", "label" =>	"Venezuela"],
            ["mapId" => "39", "shortLabel" => "DZ", "label" =>	"Algeria"],
            ["mapId" => "40", "shortLabel" => "AO", "label" =>	"Angola"],
            ["mapId" => "41", "shortLabel" => "BJ", "label" =>	"Benin"],
            ["mapId" => "42", "shortLabel" => "BW", "label" =>	"Botswana"],
            ["mapId" => "43", "shortLabel" => "BF", "label" =>	"Burkina Faso"],
            ["mapId" => "44", "shortLabel" => "BI", "label" =>	"Burundi"],
            ["mapId" => "45", "shortLabel" => "CM", "label" =>	"Cameroon"],
            ["mapId" => "46", "shortLabel" => "CV", "label" =>	"Cape Verde"],
            ["mapId" => "47", "shortLabel" => "CP", "label" =>	"Central African Republic"],
            ["mapId" => "48", "shortLabel" => "TD", "label" =>	"Chad"],
            ["mapId" => "49", "shortLabel" => "KM", "label" =>	"Comoros"],
            ["mapId" => "50", "shortLabel" => "CI", "label" =>	"Ivory Coast"],
            ["mapId" => "51", "shortLabel" => "CD", "label" =>	"DR Congo"],
            ["mapId" => "52", "shortLabel" => "DJ", "label" =>	"Djibouti"],
            ["mapId" => "53", "shortLabel" => "EG", "label" =>	"Egypt"],
            ["mapId" => "54", "shortLabel" => "GQ", "label" =>	"Equatorial Guinea"],
            ["mapId" => "55", "shortLabel" => "ER", "label" =>	"Eritrea"],
            ["mapId" => "56", "shortLabel" => "ET", "label" =>	"Ethiopia"],
            ["mapId" => "57", "shortLabel" => "GA", "label" =>	"Gabon"],
            ["mapId" => "58", "shortLabel" => "GH", "label" =>	"Ghana"],
            ["mapId" => "59", "shortLabel" => "GN", "label" =>	"Guinea"],
            ["mapId" => "60", "shortLabel" => "GW", "label" =>	"Guinea-Bissau"],
            ["mapId" => "61", "shortLabel" => "KE", "label" =>	"Kenya"],
            ["mapId" => "62", "shortLabel" => "LS", "label" =>	"Lesotho"],
            ["mapId" => "63", "shortLabel" => "LI", "label" =>	"Liberia"],
            ["mapId" => "64", "shortLabel" => "LR", "label" =>	"Libya"],
            ["mapId" => "65", "shortLabel" => "MS", "label" =>	"Madagascar"],
            ["mapId" => "66", "shortLabel" => "MW", "label" =>	"Malawi"],
            ["mapId" => "67", "shortLabel" => "ML", "label" =>	"Mali"],
            ["mapId" => "68", "shortLabel" => "MR", "label" =>	"Mauritania"],
            ["mapId" => "69", "shortLabel" => "MA", "label" =>	"Morocco"],
            ["mapId" => "70", "shortLabel" => "MZ", "label" =>	"Mozambique"],
            ["mapId" => "71", "shortLabel" => "NA", "label" =>	"Namibia"],
            ["mapId" => "72", "shortLabel" => "NE", "label" =>	"Niger"],
            ["mapId" => "73", "shortLabel" => "NG", "label" =>	"Nigeria"],
            ["mapId" => "74", "shortLabel" => "RW", "label" =>	"Rwanda"],
            ["mapId" => "75", "shortLabel" => "ST", "label" =>	"Sao Tome and Principe"],
            ["mapId" => "76", "shortLabel" => "SN", "label" =>	"Senegal"],
            ["mapId" => "77", "shortLabel" => "SC", "label" =>	"Seychelles"],
            ["mapId" => "78", "shortLabel" => "SL", "label" =>	"Sierra Leone"],
            ["mapId" => "79", "shortLabel" => "SO", "label" =>	"Somalia"],
            ["mapId" => "80", "shortLabel" => "ZA", "label" =>	"South Africa"],
            ["mapId" => "81", "shortLabel" => "SD", "label" =>	"Republic of Sudan"],
            ["mapId" => "82", "shortLabel" => "SZ", "label" =>	"Swaziland"],
            ["mapId" => "83", "shortLabel" => "TZ", "label" =>	"Tanzania"],
            ["mapId" => "84", "shortLabel" => "TG", "label" =>	"Togo"],
            ["mapId" => "85", "shortLabel" => "TN", "label" =>	"Tunisia"],
            ["mapId" => "86", "shortLabel" => "UG", "label" =>	"Uganda"],
            ["mapId" => "87", "shortLabel" => "WA", "label" =>	"Western Sahara"],
            ["mapId" => "88", "shortLabel" => "ZM", "label" =>	"Zambia"],
            ["mapId" => "89", "shortLabel" => "ZW", "label" =>	"Zimbabwe"],
            ["mapId" => "90", "shortLabel" => "GM", "label" =>	"Gambia"],
            ["mapId" => "91", "shortLabel" => "CG", "label" =>	"Congo"],
            ["mapId" => "92", "shortLabel" => "MI", "label" =>	"Mauritius"],
            ["mapId" => "93", "shortLabel" => "AF", "label" =>	"Afghanistan"],
            ["mapId" => "94", "shortLabel" => "AM", "label" =>	"Armenia"],
            ["mapId" => "95", "shortLabel" => "AZ", "label" =>	"Azerbaijan"],
            ["mapId" => "96", "shortLabel" => "BD", "label" =>	"Bangladesh"],
            ["mapId" => "97", "shortLabel" => "BT", "label" =>	"Bhutan"],
            ["mapId" => "98", "shortLabel" => "BN", "label" =>	"Brunei"],
            ["mapId" => "99", "shortLabel" => "MM", "label" =>	"Burma (Myanmar)"],
            ["mapId" => "100", "shortLabel" => "KH", "label" =>	"Cambodia"],
            ["mapId" => "101", "shortLabel" => "CN", "label" =>	"China"],
            ["mapId" => "102", "shortLabel" => "TP", "label" =>	"Timor-Leste"],
            ["mapId" => "103", "shortLabel" => "GE", "label" =>	"Georgia"],
            ["mapId" => "104", "shortLabel" => "IN", "label" =>	"India"],
            ["mapId" => "105", "shortLabel" => "ID", "label" =>	"Indonesia"],
            ["mapId" => "106", "shortLabel" => "IA", "label" =>	"Iran"],
            ["mapId" => "107", "shortLabel" => "JP", "label" =>	"Japan"],
            ["mapId" => "108", "shortLabel" => "KZ", "label" =>	"Kazakhstan"],
            ["mapId" => "109", "shortLabel" => "KP", "label" =>	"Korea (north)"],
            ["mapId" => "110", "shortLabel" => "KR", "label" =>	"Korea (south)"],
            ["mapId" => "111", "shortLabel" => "KG", "label" =>	"Kyrgyzstan"],
            ["mapId" => "112", "shortLabel" => "LA", "label" =>	"Laos"],
            ["mapId" => "113", "shortLabel" => "MY", "label" =>	"Malaysia"],
            ["mapId" => "114", "shortLabel" => "MN", "label" =>	"Mongolia"],
            ["mapId" => "115", "shortLabel" => "NP", "label" =>	"Nepal"],
            ["mapId" => "116", "shortLabel" => "PK", "label" =>	"Pakistan"],
            ["mapId" => "117", "shortLabel" => "PH", "label" =>	"Philippines"],
            ["mapId" => "118", "shortLabel" => "RU", "label" =>	"Russia"],
            ["mapId" => "119", "shortLabel" => "SG", "label" =>	"Singapore"],
            ["mapId" => "120", "shortLabel" => "LK", "label" =>	"Sri Lanka"],
            ["mapId" => "121", "shortLabel" => "TJ", "label" =>	"Tajikistan"],
            ["mapId" => "122", "shortLabel" => "TH", "label" =>	"Thailand"],
            ["mapId" => "123", "shortLabel" => "TM", "label" =>	"Turkmenistan"],
            ["mapId" => "124", "shortLabel" => "UZ", "label" =>	"Uzbekistan"],
            ["mapId" => "125", "shortLabel" => "VN", "label" =>	"Vietnam"],
            ["mapId" => "129", "shortLabel" => "AL", "label" =>	"Albania"],
            ["mapId" => "130", "shortLabel" => "AD", "label" =>	"Andorra"],
            ["mapId" => "131", "shortLabel" => "AT", "label" =>	"Austria"],
            ["mapId" => "132", "shortLabel" => "BY", "label" =>	"Belarus"],
            ["mapId" => "133", "shortLabel" => "BE", "label" =>	"Belgium"],
            ["mapId" => "134", "shortLabel" => "BH", "label" =>	"Bosnia and Herzegovina"],
            ["mapId" => "135", "shortLabel" => "BG", "label" =>	"Bulgaria"],
            ["mapId" => "136", "shortLabel" => "HY", "label" =>	"Croatia"],
            ["mapId" => "137", "shortLabel" => "CZ", "label" =>	"Czech Republic"],
            ["mapId" => "138", "shortLabel" => "DK", "label" =>	"Denmark"],
            ["mapId" => "139", "shortLabel" => "EE", "label" =>	"Estonia"],
            ["mapId" => "140", "shortLabel" => "FI", "label" =>	"Finland"],
            ["mapId" => "141", "shortLabel" => "FR", "label" =>	"France"],
            ["mapId" => "142", "shortLabel" => "DE", "label" =>	"Germany"],
            ["mapId" => "143", "shortLabel" => "GR", "label" =>	"Greece"],
            ["mapId" => "144", "shortLabel" => "HU", "label" =>	"Hungary"],
            ["mapId" => "145", "shortLabel" => "IS", "label" =>	"Iceland"],
            ["mapId" => "146", "shortLabel" => "IR", "label" =>	"Ireland"],
            ["mapId" => "147", "shortLabel" => "IT", "label" =>	"Italy"],
            ["mapId" => "148", "shortLabel" => "LV", "label" =>	"Latvia"],
            ["mapId" => "149", "shortLabel" => "LN", "label" =>	"Liechtenstein"],
            ["mapId" => "150", "shortLabel" => "LT", "label" =>	"Lithuania"],
            ["mapId" => "151", "shortLabel" => "LU", "label" =>	"Luxembourg"],
            ["mapId" => "152", "shortLabel" => "MK", "label" =>	"Macedonia"],
            ["mapId" => "153", "shortLabel" => "MT", "label" =>	"Malta"],
            ["mapId" => "154", "shortLabel" => "MV", "label" =>	"Moldova"],
            ["mapId" => "155", "shortLabel" => "MC", "label" =>	"Monaco"],
            ["mapId" => "156", "shortLabel" => "MG", "label" =>	"Montenegro"],
            ["mapId" => "157", "shortLabel" => "NL", "label" =>	"Netherlands"],
            ["mapId" => "158", "shortLabel" => "NO", "label" =>	"Norway"],
            ["mapId" => "159", "shortLabel" => "PL", "label" =>	"Poland"],
            ["mapId" => "160", "shortLabel" => "PT", "label" =>	"Portugal"],
            ["mapId" => "161", "shortLabel" => "RO", "label" =>	"Romania"],
            ["mapId" => "162", "shortLabel" => "SM", "label" =>	"San Marino"],
            ["mapId" => "163", "shortLabel" => "CS", "label" =>	"Serbia"],
            ["mapId" => "164", "shortLabel" => "SK", "label" =>	"Slovakia"],
            ["mapId" => "165", "shortLabel" => "SI", "label" =>	"Slovenia"],
            ["mapId" => "166", "shortLabel" => "ES", "label" =>	"Spain"],
            ["mapId" => "167", "shortLabel" => "SE", "label" =>	"Sweden"],
            ["mapId" => "168", "shortLabel" => "CH", "label" =>	"Switzerland"],
            ["mapId" => "169", "shortLabel" => "UA", "label" =>	"Ukraine"],
            ["mapId" => "170", "shortLabel" => "UK", "label" =>	"United Kingdom"],
            ["mapId" => "171", "shortLabel" => "VA", "label" =>	"Vatican City"],
            ["mapId" => "172", "shortLabel" => "CY", "label" =>	"Cyprus"],
            ["mapId" => "173", "shortLabel" => "TK", "label" =>	"Turkey"],
            ["mapId" => "175", "shortLabel" => "AU", "label" =>	"Australia"],
            ["mapId" => "176", "shortLabel" => "FJ", "label" =>	"Fiji"],
            ["mapId" => "177", "shortLabel" => "KI", "label" =>	"Kiribati"],
            ["mapId" => "178", "shortLabel" => "MH", "label" =>	"Marshall Islands"],
            ["mapId" => "179", "shortLabel" => "FM", "label" =>	"Micronesia"],
            ["mapId" => "180", "shortLabel" => "NR", "label" =>	"Nauru"],
            ["mapId" => "181", "shortLabel" => "NZ", "label" =>	"New Zealand"],
            ["mapId" => "182", "shortLabel" => "PW", "label" =>	"Republic of Palau"],
            ["mapId" => "183", "shortLabel" => "PG", "label" =>	"Papua New Guinea"],
            ["mapId" => "184", "shortLabel" => "WS", "label" =>	"Samoa"],
            ["mapId" => "185", "shortLabel" => "SB", "label" =>	"Solomon Islands"],
            ["mapId" => "186", "shortLabel" => "TO", "label" =>	"Tonga"],
            ["mapId" => "187", "shortLabel" => "TV", "label" =>	"Tuvalu"],
            ["mapId" => "188", "shortLabel" => "VU", "label" =>	"Vanuatu"],
            ["mapId" => "189", "shortLabel" => "NC", "label" =>	"New Caledonia"],
            ["mapId" => "190", "shortLabel" => "BA", "label" =>	"Bahrain"],
            ["mapId" => "191", "shortLabel" => "IZ", "label" =>	"Iraq"],
            ["mapId" => "192", "shortLabel" => "IE", "label" =>	"Israel"],
            ["mapId" => "193", "shortLabel" => "JO", "label" =>	"Jordan"],
            ["mapId" => "194", "shortLabel" => "KU", "label" =>	"Kuwait"],
            ["mapId" => "195", "shortLabel" => "LB", "label" =>	"Lebanon"],
            ["mapId" => "196", "shortLabel" => "OM", "label" =>	"Oman"],
            ["mapId" => "197", "shortLabel" => "QA", "label" =>	"Qatar"],
            ["mapId" => "198", "shortLabel" => "SA", "label" =>	"Saudi Arabia"],
            ["mapId" => "199", "shortLabel" => "SY", "label" =>	"Syria"],
            ["mapId" => "200", "shortLabel" => "AE", "label" =>	"UnitedArabEmirates"],
            ["mapId" => "201", "shortLabel" => "YM", "label" =>	"Yemen"],
            ["mapId" => "202", "shortLabel" => "PR", "label" =>	"Puerto Rico"],
            ["mapId" => "203", "shortLabel" => "KY", "label" =>	"Cayman Islands"],
            ["mapId" => "204", "shortLabel" => "SS", "label" =>	"South Sudan"],
            ["mapId" => "205", "shortLabel" => "KO", "label" =>	"Kosovo"],
            ["mapId" => "206", "shortLabel" => "AB", "label" =>	"Aruba"],
            ["mapId" => "207", "shortLabel" => "AN", "label" =>	"Anguilla"],
            ["mapId" => "208", "shortLabel" => "AS", "label" =>	"American Samoa"],
            ["mapId" => "209", "shortLabel" => "BM", "label" =>	"Bermuda"],
            ["mapId" => "210", "shortLabel" => "BU", "label" =>	"BES Islands"],
            ["mapId" => "211", "shortLabel" => "CC", "label" =>	"Cocos (Keeling) Islands"],
            ["mapId" => "212", "shortLabel" => "CK", "label" =>	"Cook Islands"],
            ["mapId" => "213", "shortLabel" => "CT", "label" =>	"Christmas Island"],
            ["mapId" => "214", "shortLabel" => "CW", "label" =>	"Curacao"],
            ["mapId" => "215", "shortLabel" => "FA", "label" =>	"Faroe Islands"],
            ["mapId" => "216", "shortLabel" => "FP", "label" =>	"French Polynesia"],
            ["mapId" => "217", "shortLabel" => "GI", "label" =>	"Gibraltar"],
            ["mapId" => "218", "shortLabel" => "GO", "label" =>	"Guam"],
            ["mapId" => "219", "shortLabel" => "GP", "label" =>	"Guadeloupe"],
            ["mapId" => "220", "shortLabel" => "GS", "label" =>	"Gaza Strip"],
            ["mapId" => "221", "shortLabel" => "GU", "label" =>	"Guernsey"],
            ["mapId" => "222", "shortLabel" => "IM", "label" =>	"Isle of Man"],
            ["mapId" => "223", "shortLabel" => "JS", "label" =>	"Jersey"],
            ["mapId" => "224", "shortLabel" => "KS", "label" =>	"Kingman Reef"],
            ["mapId" => "225", "shortLabel" => "MD", "label" =>	"Maldives"],
            ["mapId" => "226", "shortLabel" => "ME", "label" =>	"Montserrat"],
            ["mapId" => "227", "shortLabel" => "MP", "label" =>	"Mayotte"],
            ["mapId" => "228", "shortLabel" => "MQ", "label" =>	"Martinique"],
            ["mapId" => "229", "shortLabel" => "NF", "label" =>	"Norfolk Island"],
            ["mapId" => "230", "shortLabel" => "NM", "label" =>	"Northern Mariana Islands"],
            ["mapId" => "231", "shortLabel" => "NU", "label" =>	"Niue"],
            ["mapId" => "232", "shortLabel" => "PI", "label" =>	"Pitcairn Islands"],
            ["mapId" => "233", "shortLabel" => "RE", "label" =>	"La Réunion"],
            ["mapId" => "234", "shortLabel" => "SF", "label" =>	"Sint Maarten"],
            ["mapId" => "235", "shortLabel" => "SH", "label" =>	"Saint Helena"],
            ["mapId" => "236", "shortLabel" => "SP", "label" =>	"Saint Pierre and Miquelon"],
            ["mapId" => "237", "shortLabel" => "TC", "label" =>	"Turks and Caicos Islands"],
            ["mapId" => "238", "shortLabel" => "VK", "label" =>	"Virgin Islands (UK)"],
            ["mapId" => "239", "shortLabel" => "VS", "label" =>	"Virgin Islands (US)"],
            ["mapId" => "240", "shortLabel" => "WE", "label" =>	"Palestine"],
            ["mapId" => "241", "shortLabel" => "WF", "label" =>	"Wallis and Futuna"],
            ["mapId" => "242", "shortLabel" => "WC", "label" =>	"Cape Town"],
            ["mapId" => "243", "shortLabel" => "LP", "label" =>	"La Paz"],
            ["mapId" => "244", "shortLabel" => "AB", "label" =>	"Abkhazia"],
            ["mapId" => "245", "shortLabel" => "NA", "label" =>	"Netherlands Antilles"],
            ["mapId" => "246", "shortLabel" => "NC", "label" =>	"Northern Cyprus"],
            ["mapId" => "247", "shortLabel" => "SV", "label" =>	"Svalbard"],
            ["mapId" => "248", "shortLabel" => "TK", "label" =>	"Tokelau"]
        ]);

        for($i = 0; $i < count($countries); $i++) {
            Country::create([
                'mapId' => $countries[$i]['mapId'],
                'shortLabel' => $countries[$i]['shortLabel'],
                'label' => $countries[$i]['label'],
            ]);
        }
    }
}