name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Invoke deployment hook
      uses: jbrooksuk/laravel-forge-action@v1.0.2
      with:
        trigger_url: ${{ secrets.TRIGGER_URL }}


